parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_postgresql'
        server_version: '9.5'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
        schema_filter: /^prdt._d_currency$/
        mapping_types:
            enum: string
            set: string
            _bpchar: string
            name: string
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        second_level_cache:
            enabled: false
            log_enabled: true
            region_lock_lifetime: 120
            regions:
                my_entity_region:
                    type: default
                    lifetime: 3600
                    
                    
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
